{{ if .Values.sshHostPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ssh
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: ssh
    port: {{ .Values.sshPort | int }}
    targetPort: ssh
    nodePort: {{ .Values.sshHostPort | int }}
  selector:
    app: {{ template "fullname" . }}
{{ end }}
